
# Where to store logs/checkpoints

tensorboard_log_dir: "log_dir"
data_folder: "data/"
checkpoints_folder: "checkpoints/srgan"


# Image preprocess

image_crop: 384
downsampling_factor: 4


num_res_block: 16

adv_loss_rate: 0.001

adam_b: 0.9

lr: 0.0001

lr_step_size: 10000

lr_step: 0.1



batch_size: 1

num_workers: 4

